"""Modus XML — import (ModusResult) and export (ModusSubmit) for soil tests.

The AgGateway Modus standard defines two primary document types:
- ModusResult: Lab results (parsed by ``parse_modus_xml``)
- ModusSubmit: Work orders (generated by ``generate_modus_submit``)
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any
from xml.etree import ElementTree as ET
from xml.etree.ElementTree import Element

from defusedxml import ElementTree

from openfmis.schemas.field_event import SoilTestEntry, SoilTestEventData

log = logging.getLogger(__name__)

# Common Modus XML namespaces
MODUS_NS = {
    "m": "http://www.aggateway.org/Modus",
    "": "http://www.aggateway.org/Modus",
}

# Modus analyte codes → standard parameter names
ANALYTE_MAP: dict[str, str] = {
    "pH": "pH",
    "PH": "pH",
    "P": "P",
    "PHOSPHORUS": "P",
    "K": "K",
    "POTASSIUM": "K",
    "OM": "OM",
    "ORGANIC MATTER": "OM",
    "CEC": "CEC",
    "S": "S",
    "SULFUR": "S",
    "ZN": "Zn",
    "ZINC": "Zn",
    "MN": "Mn",
    "MANGANESE": "Mn",
    "FE": "Fe",
    "IRON": "Fe",
    "CU": "Cu",
    "COPPER": "Cu",
    "B": "B",
    "BORON": "B",
    "CA": "Ca",
    "CALCIUM": "Ca",
    "MG": "Mg",
    "MAGNESIUM": "Mg",
    "NA": "Na",
    "SODIUM": "Na",
    "NO3": "NO3",
    "NITRATE": "NO3",
    "SO4": "SO4",
    "SULFATE": "SO4",
    "BUF_PH": "Buffer pH",
    "BUFFER PH": "Buffer pH",
    "BUFFER_PH": "Buffer pH",
}

# Modus unit codes → standard unit strings
UNIT_MAP: dict[str, str] = {
    "ppm": "ppm",
    "PPM": "ppm",
    "mg/kg": "ppm",
    "%": "%",
    "percent": "%",
    "meq/100g": "meq/100g",
    "cmol/kg": "meq/100g",
    "lbs/A": "lbs/ac",
    "lbs/ac": "lbs/ac",
    "kg/ha": "kg/ha",
}


class ModusParseError(Exception):
    """Raised when the Modus XML cannot be parsed."""


class ModusParseResult:
    """Result of parsing a Modus XML file."""

    def __init__(self) -> None:
        self.lab_name: str | None = None
        self.report_date: datetime | None = None
        self.samples: list[dict[str, Any]] = []
        self.warnings: list[str] = []

    @property
    def sample_count(self) -> int:
        return len(self.samples)


def parse_modus_xml(xml_content: str | bytes) -> ModusParseResult:
    """Parse a Modus XML document and extract soil test results.

    Supports both namespaced and non-namespaced Modus XML.
    Returns a ModusParseResult with samples and warnings.
    """
    try:
        root = ElementTree.fromstring(xml_content)
    except Exception as exc:
        raise ModusParseError(f"Invalid XML: {exc}") from exc

    result = ModusParseResult()

    # Detect namespace
    ns = _detect_namespace(root)

    # Extract lab/report metadata
    result.lab_name = _find_text(root, "LabName", ns) or _find_text(root, "Laboratory", ns)
    report_date_str = _find_text(root, "ReportDate", ns) or _find_text(root, "DateReceived", ns)
    if report_date_str:
        result.report_date = _parse_date(report_date_str)

    # Find sample elements — try multiple common Modus structures
    samples_elem = _find_elem(root, "Samples", ns) or _find_elem(root, "SampleList", ns) or root

    sample_elems = _find_all(samples_elem, "Sample", ns)
    if not sample_elems:
        # Try flatter structure
        sample_elems = _find_all(root, "Sample", ns)

    if not sample_elems:
        result.warnings.append("No <Sample> elements found in document")
        return result

    for sample_elem in sample_elems:
        sample = _parse_sample(sample_elem, ns, result)
        if sample:
            result.samples.append(sample)

    return result


def modus_to_soil_event_data(
    parse_result: ModusParseResult,
) -> list[SoilTestEventData]:
    """Convert parsed Modus samples to SoilTestEventData objects.

    Each sample becomes one SoilTestEventData (which maps to one FieldEvent).
    """
    events = []
    for sample in parse_result.samples:
        entries = []
        for analyte in sample.get("analytes", []):
            entries.append(
                SoilTestEntry(
                    parameter=analyte["parameter"],
                    value=analyte["value"],
                    unit=analyte.get("unit", ""),
                    depth=sample.get("depth"),
                    depth_unit=sample.get("depth_unit"),
                )
            )

        if not entries:
            continue

        event_data = SoilTestEventData(
            lab_name=parse_result.lab_name,
            sample_date=parse_result.report_date or sample.get("date"),
            test_entries=entries,
        )
        events.append(event_data)

    return events


# ── Internal helpers ────────────────────────────────────────────────────


def _detect_namespace(root: Element) -> str:
    """Detect the XML namespace prefix from the root tag."""
    tag = root.tag
    if "{" in tag:
        return tag.split("}")[0] + "}"
    return ""


def _find_text(elem: Element, tag: str, ns: str) -> str | None:
    """Find text content of a child element, trying with and without namespace."""
    child = elem.find(f"{ns}{tag}")
    if child is None:
        # Try without namespace
        child = elem.find(tag)
    if child is not None and child.text:
        return child.text.strip()
    return None


def _find_elem(elem: Element, tag: str, ns: str) -> Element | None:
    child = elem.find(f"{ns}{tag}")
    if child is None:
        child = elem.find(tag)
    return child


def _find_all(elem: Element, tag: str, ns: str) -> list[Element]:
    results = elem.findall(f"{ns}{tag}")
    if not results:
        results = elem.findall(tag)
    return results


def _parse_date(date_str: str) -> datetime | None:
    """Parse common date formats found in Modus XML."""
    for fmt in (
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%dT%H:%M:%SZ",
        "%Y-%m-%d",
        "%m/%d/%Y",
        "%m-%d-%Y",
    ):
        try:
            return datetime.strptime(date_str, fmt)
        except ValueError:
            continue
    return None


def _parse_sample(
    sample_elem: Element,
    ns: str,
    result: ModusParseResult,
) -> dict[str, Any] | None:
    """Parse a single <Sample> element."""
    sample: dict[str, Any] = {}

    # Sample ID
    sample["sample_id"] = (
        _find_text(sample_elem, "SampleID", ns)
        or _find_text(sample_elem, "SampleNumber", ns)
        or sample_elem.get("id", "")
    )

    # Depth
    depth_str = _find_text(sample_elem, "Depth", ns) or _find_text(sample_elem, "SampleDepth", ns)
    if depth_str:
        try:
            sample["depth"] = float(depth_str)
            sample["depth_unit"] = "inches"  # Modus default
        except ValueError:
            # Try parsing "0-6" range format → use midpoint
            if "-" in depth_str:
                parts = depth_str.split("-")
                try:
                    lo, hi = float(parts[0]), float(parts[1])
                    sample["depth"] = (lo + hi) / 2
                    sample["depth_unit"] = "inches"
                except (ValueError, IndexError):
                    pass

    depth_unit = _find_text(sample_elem, "DepthUnit", ns)
    if depth_unit:
        sample["depth_unit"] = depth_unit

    # Location
    lat = _find_text(sample_elem, "Latitude", ns)
    lon = _find_text(sample_elem, "Longitude", ns)
    if lat and lon:
        try:
            sample["latitude"] = float(lat)
            sample["longitude"] = float(lon)
        except ValueError:
            pass

    # Sample date
    date_str = _find_text(sample_elem, "SampleDate", ns) or _find_text(
        sample_elem, "DateSampled", ns
    )
    if date_str:
        sample["date"] = _parse_date(date_str)

    # Parse analytes/results
    analytes = _parse_analytes(sample_elem, ns, result)
    sample["analytes"] = analytes

    if not analytes:
        result.warnings.append(f"Sample '{sample.get('sample_id', '?')}' has no analyte results")
        return None

    return sample


def _parse_analytes(
    sample_elem: Element,
    ns: str,
    result: ModusParseResult,
) -> list[dict[str, Any]]:
    """Extract analyte measurements from a sample element."""
    analytes = []

    # Try multiple common structures
    results_elem = (
        _find_elem(sample_elem, "Results", ns)
        or _find_elem(sample_elem, "AnalyteResults", ns)
        or _find_elem(sample_elem, "TestResults", ns)
        or sample_elem
    )

    analyte_elems = (
        _find_all(results_elem, "Result", ns)
        or _find_all(results_elem, "Analyte", ns)
        or _find_all(results_elem, "TestResult", ns)
    )

    for ae in analyte_elems:
        analyte = _parse_single_analyte(ae, ns, result)
        if analyte:
            analytes.append(analyte)

    return analytes


def _parse_single_analyte(
    elem: Element,
    ns: str,
    result: ModusParseResult,
) -> dict[str, Any] | None:
    """Parse a single analyte/result element."""
    # Get analyte name/code
    name = (
        _find_text(elem, "AnalyteName", ns)
        or _find_text(elem, "Name", ns)
        or _find_text(elem, "Parameter", ns)
        or elem.get("name", "")
        or elem.get("analyte", "")
    )
    if not name:
        return None

    # Normalize to standard parameter name
    parameter = ANALYTE_MAP.get(name.upper(), ANALYTE_MAP.get(name, name))

    # Get value
    value_str = (
        _find_text(elem, "Value", ns)
        or _find_text(elem, "Result", ns)
        or _find_text(elem, "AnalyteValue", ns)
        or elem.text
    )
    if not value_str:
        return None

    # Handle "<" prefix (below detection limit)
    value_str = value_str.strip().lstrip("<>")
    try:
        value = float(value_str)
    except ValueError:
        result.warnings.append(f"Non-numeric value '{value_str}' for analyte '{name}'")
        return None

    # Get unit
    unit = _find_text(elem, "Unit", ns) or _find_text(elem, "Units", ns) or elem.get("unit", "")
    unit = UNIT_MAP.get(unit, unit)

    return {
        "parameter": parameter,
        "value": value,
        "unit": unit,
    }


# ── Modus work-order export (ModusSubmit) ──────────────────────────────


# Reverse map: canonical parameter → Modus analyte name
_REVERSE_ANALYTE: dict[str, str] = {
    "pH": "pH",
    "P": "Phosphorus",
    "K": "Potassium",
    "OM": "Organic Matter",
    "CEC": "CEC",
    "S": "Sulfur",
    "Zn": "Zinc",
    "Mn": "Manganese",
    "Fe": "Iron",
    "Cu": "Copper",
    "B": "Boron",
    "Ca": "Calcium",
    "Mg": "Magnesium",
    "Na": "Sodium",
    "NO3": "Nitrate",
    "SO4": "Sulfate",
    "Buffer pH": "Buffer pH",
}


def generate_modus_submit(
    *,
    submitter_name: str,
    lab_name: str,
    field_name: str,
    sample_points: list[dict[str, Any]],
    requested_analyses: list[str] | None = None,
    sample_depth: float | None = None,
    depth_unit: str = "inches",
    notes: str | None = None,
) -> str:
    """Generate a Modus ModusSubmit XML work order.

    Args:
        submitter_name: Name of the person/org submitting the work order.
        lab_name: Target lab name.
        field_name: Field name for reference.
        sample_points: List of dicts with ``sample_id`` (str), and optionally
            ``latitude`` (float), ``longitude`` (float).
        requested_analyses: List of canonical analyte names (e.g. ["pH", "P", "K"]).
            If None, a standard soil test panel is used.
        sample_depth: Sample depth value.
        depth_unit: Depth unit (default "inches").
        notes: Optional notes to include.

    Returns:
        UTF-8 encoded XML string.
    """
    ns = "http://www.aggateway.org/Modus"

    root = ET.Element("ModusSubmit", xmlns=ns)

    ET.SubElement(root, "SubmitterName").text = submitter_name
    ET.SubElement(root, "LabName").text = lab_name
    ET.SubElement(root, "FieldName").text = field_name
    ET.SubElement(root, "SubmitDate").text = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

    if notes:
        ET.SubElement(root, "Notes").text = notes

    # Default standard soil panel
    if requested_analyses is None:
        requested_analyses = [
            "pH",
            "P",
            "K",
            "OM",
            "CEC",
            "S",
            "Zn",
            "Mn",
            "Fe",
            "Cu",
            "B",
            "Ca",
            "Mg",
            "Na",
            "Buffer pH",
        ]

    # Requested analyses
    analyses_elem = ET.SubElement(root, "RequestedAnalyses")
    for param in requested_analyses:
        modus_name = _REVERSE_ANALYTE.get(param, param)
        ae = ET.SubElement(analyses_elem, "Analysis")
        ET.SubElement(ae, "AnalyteName").text = modus_name

    # Samples
    samples_elem = ET.SubElement(root, "Samples")
    for sp in sample_points:
        sample = ET.SubElement(samples_elem, "Sample")
        ET.SubElement(sample, "SampleID").text = str(sp.get("sample_id", ""))

        if sample_depth is not None:
            ET.SubElement(sample, "Depth").text = str(sample_depth)
            ET.SubElement(sample, "DepthUnit").text = depth_unit

        lat = sp.get("latitude")
        lon = sp.get("longitude")
        if lat is not None and lon is not None:
            ET.SubElement(sample, "Latitude").text = str(lat)
            ET.SubElement(sample, "Longitude").text = str(lon)

    ET.indent(root, space="  ")
    return ET.tostring(root, encoding="unicode", xml_declaration=True)
